version: '2'
services:

  postgres:
    container_name: postgres
    image: postgres
    expose:
      - 5432
    ports:
      - 5432:5432
    networks:
      - spring
    environment:
      POSTGRES_PASSWORD: "password"
      POSTGRES_DB: "database"
    volumes:
      - db-data:/var/lib/postgresql/data
    restart: always

  spring:
    container_name: spring
    image: spring
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - 8080
    ports:
      - 8080:8080
    networks:
      - spring
    depends_on:
      - postgres
    environment:
      POSTGRES_URL: "postgres://postgres:password@postgres:5432/database"
    restart: always

volumes:
  db-data:

networks:
  spring:
